
# frontend (React + Nginx)

# Based image
FROM node:24-slim AS builder

# Set working dir
WORKDIR /client

# Copy package*.json file first
COPY ./package.json ./package-lock.json ./

# copy the rest of application
COPY ./ ./

RUN npm install

RUN npm run build

# Serve phase
FROM nginx

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy built React app to Nginx public directory
COPY --from=builder ./client/dist /usr/share/nginx/html
COPY ./nginx_config/default.conf ./etc/nginx/conf.d/default.conf
COPY ./nginx_config/nginx.conf ./etc/nginx/nginx.conf

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]