
# frontend (React + Nginx)

# Based image
FROM node:24-slim AS builder

# Set working dir
WORKDIR /client

# Copy package*.json file first
COPY ./client/package.json ./client/.env.production ./client/package-lock.json ./

RUN npm install

# copy the rest of application
COPY ./client/ ./

RUN npm run build

#COPY ./client/ ./

# tell docker what port our app uses 
EXPOSE 80

# Serve phase
FROM nginx

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*


# Copy built React app to Nginx public directory
COPY --from=builder ./client/dist /usr/share/nginx/html
COPY ./client/nginx_config/default.conf ./etc/nginx/conf.d/default.conf
COPY ./client/nginx_config/nginx.conf ./etc/nginx/nginx.conf

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

