# Based image
FROM node:24-slim

# Set working dir
WORKDIR /server

# Copy package*.json file first
COPY ./package.json ./package-lock.json ./

# install pakages
RUN npm install

# copy the rest of application
COPY ./ ./

# tell docker what port our app uses 
EXPOSE 1111

# command to start our application
CMD [ "node" , "server.js"]