apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer  # Make Service accessable from outside cluster
  selector:
    app: hello-k8s
  ports:
    - port: 80          # Port Service listens on
      targetPort: 3000  # Port on the pods to forward to
